ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS show_avatar BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_bio BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_location BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_skills BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_languages BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_availability_status BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_website_url BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_linkedin_url BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_github_url BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_twitter_url BOOLEAN NOT NULL DEFAULT true;
